settings:
  save-user-cache-on-stop: true
  bungeecord: false
  sample-count: 12
  player-shuffle: 0
  moved-wrongly-threshold: 0.0625
  moved-too-quickly-multiplier: 10.0
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./start.sh
  netty-threads: 2
  user-cache-size: 1000
  log-villager-deaths: true
  log-named-deaths: true
  debug: false
world-settings:
  default:
    view-distance: 4
    mob-spawn-range: 4
    merge-radius:
      item: 3.5
      exp: 6.0
    entity-activation-range:
      animals: 16
      monsters: 24
      misc: 8
      tick-inactive-villagers: false
    ticks-per:
      hopper-transfer: 8
      hopper-check: 8
      hopper-amount: 1
    max-tick-time:
      tile: 50
      entity: 50
    nerf-spawner-mobs: false
    arrow-despawn-rate: 1200
    item-despawn-rate: 6000
    trident-despawn-rate: 1200
    enable-zombie-pigmen-portal-spawns: true
    zombie-aggressive-towards-villager: true
